# Generated by Django 3.1.3 on 2021-07-05 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarapp', '0004_auto_20210706_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='f_month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day', to='calendarapp.month'),
        ),
        migrations.AlterField(
            model_name='day',
            name='f_ymd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day', to='calendarapp.ymd'),
        ),
        migrations.AlterField(
            model_name='month',
            name='f_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='month', to='calendarapp.year'),
        ),
        migrations.AlterField(
            model_name='time',
            name='f_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='time',
            name='f_ymd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time', to='calendarapp.ymd'),
        ),
    ]
