# Generated by Django 3.2 on 2021-07-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_auto_20210708_0341'),
        ('calendarapp', '0005_auto_20210706_0411'),
    ]

    operations = [
    ]
