# Generated by Django 3.1.3 on 2021-07-11 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_auto_20210706_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='o_time',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_event_title', models.CharField(blank=True, max_length=100, null=True)),
                ('o_event_time', models.CharField(blank=True, max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now=True, null=True)),
                ('f_ymd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='calendarapp.ymd')),
            ],
        ),
        migrations.AddField(
            model_name='time',
            name='f_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time', to='calendarapp.event'),
        ),
    ]
