# Generated by Django 3.1.3 on 2021-07-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0006_auto_20210712_0440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='remain',
        ),
        migrations.AddField(
            model_name='event',
            name='remain',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
