# Generated by Django 3.2 on 2021-07-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_auto_20210706_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='watches',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
