# Generated by Django 3.2 on 2021-06-28 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, null=True, unique=True)),
                ('description', models.TextField(help_text='소개', null=True)),
                ('github', models.URLField(max_length=30, null=True)),
                ('blog', models.URLField(max_length=30, null=True)),
                ('image', models.ImageField(help_text='대표 이미지', null=True, upload_to='profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accountapp.user')),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
