# Generated by Django 3.2 on 2021-06-30 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='notice_thumbnail/')),
                ('content', froala_editor.fields.FroalaField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
