# Generated by Django 3.2 on 2021-06-30 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
