# Generated by Django 3.2 on 2021-07-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0005_alter_notice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='watches',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
