# Generated by Django 3.2 on 2021-06-27 17:16

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20210603_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=froala_editor.fields.FroalaField(default=1),
            preserve_default=False,
        ),
    ]
